# Generated by Django 5.1.4 on 2024-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_id', models.CharField(max_length=100, unique=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('flight_no', models.CharField(max_length=100)),
                ('flight_date', models.DateField()),
                ('pieces', models.IntegerField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('goods_approved', models.BooleanField(default=False)),
                ('manifest', models.CharField(blank=True, max_length=255, null=True)),
                ('execute_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
